@startuml
title Accounts

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary("BankAppApplication.BankAppApplication_boundary", "BankAppApplication", $tags="") {
  Component(BankAppApplication.BankAppApplication.Accounts, "Accounts", "Module", "", $tags="")
}


SHOW_LEGEND(true)
@enduml