server:
  port: ${PORT:8081}
  ssl:
    bundle: "server"
    enabled-protocols: TlSv1.3

spring:
  application:
    name: psp-mediator-service
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "psp-lawify"
          keystore:
            location: "classpath:keystore.p12"
            password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:cert.pem"
  # db config
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5401/psp-mediator-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  activemq:
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER:admin}
    password: ${BROKER_PASSWORD:admin}
    pool:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

api-key:
  encrypt: ${ENCRYPT_KEY:6091297EBCE882EC01F71E4AF3D0812A205045AB892F75769FB1F7B11BAF47C7}

token:
  jwt:
    key: ${JWT_KEY:66556A576E5A7234753778214125442A472D4B6150645367566B59703273357638792F423F4528482B4D6251655468576D5A7134743677397A24432646294A40}
    duration: ${JWT_DURATION:90000000}

stripe:
  key: ${STRIPE_KEY:sk_test_51ORI4UG8LvERJLgsIbRRXqzwT1kOTUHYJ52g1UlTJXIENmIsvtjunCnKmopV46v510x1FVc30E60HP69P6PU9FYr00FJGpTzsi}
  endpoint-secret: ${STRIPE_ENDPOINT_SECRET:whsec_1EKlayY84BkWVo1F5wLlglZMSyntucBp}

payment:
  fe-base-url: ${FE_URL:http://localhost:5173}
  success-url: subscription-payment-success
  error_url: https://
  failed-url: subscription-payment-failed

hash:
  salt: cgYte9e7r2



