server:
  port: ${PORT:8083}

spring:
  application:
    name: paypal-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

paypal:
  client:
    id: CLIENT_ID
    secret: CLIENT_SECRET
  mode: sandbox