server:
  port: ${PORT:8083}

spring:
  application:
    name: paypal-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5402/paypal-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  activemq:
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER:admin}
    password: ${BROKER_PASSWORD:admin}
    pool:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

paypal:
  client:
    id: Aa1u29AHYoRdBI98eBNq5n_Z9ynTykQyIWQ_XMNMSZW2EAI8HUpEgMVLAGcEGrQRvkp-ohPJFOjkE-9P
    secret: EI_OtAt99_AGZ86mj_YXsnSGUTiRTzm0yhh238pJdR6c9sQmXT6e_x9w-4hov_xgv4WCHq-G_QIib9Yv
  mode: sandbox