server:
  port: ${PORT:8082}
  ssl:
    bundle: psp-lawify
    enabled-protocols: TlSv1.3

spring:
  application:
    name: card-service
  ssl:
    bundle:
      jks:
        psp-lawify:
          key:
            alias: "psp-lawify"
          keystore:
            location: "classpath:dev-keystore.p12"
            password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:dev-cert.pem"
  activemq:
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER:admin}
    password: ${BROKER_PASSWORD:admin}
    pool:
      enabled: true


eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port:8081}
    status-page-url: https://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/actuator/health
    home-page-url: https://${eureka.instance.hostname}:${server.port}/
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://localhost:8761/eureka}
    tls:
      enabled: true
      key-store: "classpath:dev-keystore.p12"
      key-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
      key-store-type: "PKCS12"
      trust-store: "classpath:dev-keystore.p12"
      trust-store-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
      trust-store-type: PKCS12
      key-store-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}

bank:
  baseUrl: https://localhost:7000
  transactionPath: /Transactions/MakeTransaction?transactionId=

