server:
  port: ${PORT:8085}
  ssl:
    bundle: psp-lawify
    enabled-protocols: TlSv1.3

spring:
  application:
    name: crypto-service

  ssl:
    bundle:
      jks:
        psp-lawify:
          key:
            alias: "psp-lawify"
          keystore:
            location: "classpath:dev-keystore.p12"
            password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:dev-cert.pem"

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5403/crypto-db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  activemq:
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER:admin}
    password: ${BROKER_PASSWORD:admin}
    pool:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://localhost:8761/eureka}
    tls:
      enabled: true
      key-store: "classpath:dev-keystore.p12"
      key-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
      key-store-type: "PKCS12"
      trust-store: "classpath:dev-keystore.p12"
      trust-store-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}
      trust-store-type: PKCS12
      key-store-password: ${KEYSTORE_PASS:22Nn5pvlJgmWR51Z}

hash:
  salt: cgYte9e7r2

api-key:
  encrypt: ${ENCRYPT_KEY:6091297EBCE882EC01F71E4AF3D0812A205045AB892F75769FB1F7B11BAF47C7}

coingate:
  url: https://api-sandbox.coingate.com/v2/orders