version: '3.8'
name: psp-dev
services:
  agency-db:
    image: postgres
    container_name: agency-db
    restart: always
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: agency-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - agency-data:/var/lib/postgresql/data
    networks:
      psp-net:
  psp-mediator-db:
    image: postgres
    container_name: psp-mediator-db
    restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: psp-mediator-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - psp-mediator-data:/var/lib/postgresql/data
    networks:
      psp-net:
  paypal-db:
    image: postgres
    container_name: paypal-db
    restart: always
    ports:
      - "5402:5432"
    environment:
      POSTGRES_DB: paypal-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - paypal-data:/var/lib/postgresql/data
    networks:
      psp-net:
  crypto-db:
    image: postgres
    container_name: crypto-db
    restart: always
    ports:
      - "5403:5432"
    environment:
      POSTGRES_DB: crypto-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - crypto-data:/var/lib/postgresql/data
    networks:
      psp-net:
  psp-activemq:
    image: rmohr/activemq
    ports:
      - "8161:8161"  # Web Console
      - "61616:61616" # JMS
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_WRITE_LOGIN=writer
      - ACTIVEMQ_WRITE_PASSWORD=writer
      - ACTIVEMQ_READ_LOGIN=reader
      - ACTIVEMQ_READ_PASSWORD=reader
    volumes:
      - psp-activemq-data:/data/activemq
      - psp-activemq-logs:/var/log/activemq
networks:
  psp-net:
    driver: bridge
volumes:
  agency-data:
    driver: local
  bank-app-data:
    driver: local
  psp-mediator-data:
    driver: local
  paypal-data:
    driver: local
  crypto-data:
    driver: local
  psp-activemq-data:
    driver: local
  psp-activemq-logs:
    driver: local